=== NgocHHine/HT_XML/Buoi2/company.dtd
<!ELEMENT company (dep:department+, xin:xintream+)>

<!ELEMENT dep:department (hr:employee+)>
<!ATTLIST dep:department
    name CDATA #REQUIRED
>

<!ELEMENT xin:xintream (hr:employee+)>
<!ATTLIST xin:xintream
    name CDATA #REQUIRED
>

<!ELEMENT hr:employee (hr:name, hr:position)>
<!ATTLIST hr:employee
    id ID #REQUIRED
>

<!ELEMENT hr:name (#PCDATA)>
<!ELEMENT hr:position (#PCDATA)>

=== NgocHHine/HT_XML/nhansu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "company.dtd">
<company xmlns:hr="http://company.com/hr"
         xmlns:dep="http://company.com/department"
         xmlns:xin="http://company.com/xintream">

    <dep:department name="Kế toán">
        <hr:employee id="KT1">
            <hr:name>Nguyễn Thị Loan</hr:name>
            <hr:position>Kế toán trưởng</hr:position>
        </hr:employee>
        <hr:employee id="KT2">
            <hr:name>Trần Thị Nam Em</hr:name>
            <hr:position>Kế toán viên</hr:position>
        </hr:employee>
    </dep:department>

    <xin:xintream name="Maketing">
        <hr:employee id="MK1">
            <hr:name>Dương Anh Chí</hr:name>
            <hr:position>Nhân viên Maketing</hr:position>
        </hr:employee>
    </xin:xintream>
</company>
