<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library [
    <!ELEMENT library (book+)>
    <!ELEMENT book (title, author, year, genre)>
    <!ATTLIST book id ID #REQUIRED>

    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
]>
<library>
    <book id="KT01">
        <title>Lập trình Python</title>
        <author>Nguyễn Văn Chính</author>
        <year>2022</year>
        <genre>Công nghệ</genre>
    </book>

    <book id="KT02">
        <title>Kinh tế học cơ bản</title>
        <author>Trần Thị Dương</author>
        <year>2019</year>
        <genre>Kinh tế</genre>
    </book>

    <book id="KT03">
        <title>Lập trình Web nâng cao</title>
        <author>Lê Văn Em</author>
        <year>2019</year>
        <genre>Công nghệ</genre>
    </book>

      <book id="KT06">
        <title>Lập trình hướng đối tượng</title>
        <author>Trần Văn Linh</author>
        <year>2009</year>
        <genre>Công nghệ</genre>
    </book>
</library>
